export const monthDetails = [
  {
    month: "Apr",
    month_id: 4,
    isCheckBox: false,
  },
  {
    month: "May",
    month_id: 5,
    isCheckBox: false,
  },
  {
    month: "Jun",
    month_id: 6,
    isCheckBox: false,
  },
  {
    month: "Jul",
    month_id: 7,
    isCheckBox: false,
  },
  {
    month: "Aug",
    month_id: 8,
    isCheckBox: false,
  },
  {
    month: "Sep",
    month_id: 9,
    isCheckBox: false,
  },
  {
    month: "Oct",
    month_id: 10,
    isCheckBox: false,
  },
  {
    month: "Nov",
    month_id: 11,
    isCheckBox: false,
  },
  {
    month: "Dec",
    month_id: 12,
    isCheckBox: false,
  },
  {
    month: "Jan",
    month_id: 1,
    isCheckBox: false,
  },
  {
    month: "Feb",
    month_id: 2,
    isCheckBox: false,
  },
  {
    month: "Mar",
    month_id: 3,
    isCheckBox: false,
  },
  {
    month: "Apr",
    month_id: 13,
    isCheckBox: false,
  },
  {
    month: "May",
    month_id: 14,
    isCheckBox: false,
  },
];

export const tableFeeData = [
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 4,
    month_name: "",
    status: "none",
  },
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 5,
    month_name: "",
    status: "none",
  },
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 6,
    month_name: "",
    status: "none",
  },
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 7,
    month_name: "",
    status: "none",
  },
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 8,
    month_name: "",
    status: "none",
  },
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 9,
    month_name: "",
    status: "none",
  },
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 10,
    month_name: "",
    status: "none",
  },
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 11,
    month_name: "",
    status: "none",
  },
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 12,
    month_name: "",
    status: "none",
  },
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 1,
    month_name: "",
    status: "none",
  },
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 2,
    month_name: "",
    status: "none",
  },
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 3,
    month_name: "",
    status: "none",
  },
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 13,
    month_name: "",
    status: "none",
  },
  {
    amt: "",
    bal_to_be_paid: 0,
    due_date: "",
    month_id: 14,
    month_name: "",
    status: "none",
  },

];
